### ISSUE TITLE
running the Convert.py file 

### ISSUE THREAD

**Issue by Jorgegarcia197** [deeplearningais/curfil#23]
I am trying to run the convert.py file and I get the following error 
Traceback (most recent call last):
  File "scripts/NYU/convert.py", line 180, in <module>
    Parallel(num_threads)(delayed(convert_image)(i, scenes[i], depth[i, :, :].T, images[i, :, :].T, labels[i, :, :].T) for i in range(len(images)))
  File "/home/jorgegarciaserna/project/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/jorgegarciaserna/project/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/jorgegarciaserna/project/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
**struct.error: required argument is not an integer**

**Comment by xctspring** [comment]
Hi,

Have you solved it? I have the same problem.

**Comment by bishwarup307** [comment]
check https://github.com/deeplearningais/curfil/pull/24 for the solution.
